platforms = {
	"UA": "usaco.org", 
  "ACM": "acmu.ru", 
  "CF": "codechef.com", 
  "EOL":"e-olimp.com", 
  "IFM": "neerc.ifmo.ru/school", 
  "CH24": "ch24.org", 
  "HR": "hackerrank.com", 
  "HE": "hackerearth.com", 
  "OC": "opencup.ru", 
  "ACM": "acm.dvpion.ru", 
  "ICPC": "icfpcontest.org", 
  "GCJ": "google.com/codejam", 
  "DE24": "deadline24.pl", 
  "IOI": "stats.ioinformatics.org", 
  "PE": "projecteuler.net", 
  "SN": "contests.snarknews.info", 
  "CG": "codingame.com", 
  "ACMP": "acmp.ru", 
  "CFR": "codeforces.ru",
  "CF": "codeforces.com", 
  "ELY": "e-olymp.com",
  "DMOJ": "dmoj.ca",
  "MARA": "marathon24.com",
  "IPSC": "ipsc.ksp.sk", 
  "RCC": "russiancodecup.ru",
  "UVA": "uva.onlinejudge.org",
  "TIM": "acm.timus.ru",
  "OPEN": "opener.itransition.com", 
  "YANDEX": "algorithm.contest.yandex.ru",
  "HSIN": "hsin.hr/coci",
  "CFT": "ctftime.org", 
  "KA": "kaggle.com",
  "TC": "topcoder.com",
  "GSU": "dl.gsu.by", 
  "FBHC": "facebook.com/hackercup"
}