platforms = {
	"UA": "usaco.org",
  "CC": "codechef.com", 
  "EOL":"e-olimp.com",
  "CH24": "ch24.org", 
  "HR": "hackerrank.com", 
  "HE": "hackerearth.com",
  "ICPC": "icfpcontest.org", 
  "GCJ": "google.com/codejam", 
  "DE24": "deadline24.pl", 
  "IOI": "stats.ioinformatics.org", 
  "PE": "projecteuler.net", 
  "SN": "contests.snarknews.info", 
  "CG": "codingame.com", 
  "CF": "codeforces.com", 
  "ELY": "e-olymp.com",
  "DMOJ": "dmoj.ca",
  "MARA": "marathon24.com",
  "IPSC": "ipsc.ksp.sk", 
  "UVA": "uva.onlinejudge.org",
  "OPEN": "opener.itransition.com", 
  "HSIN": "hsin.hr/coci",
  "CFT": "ctftime.org", 
  "KA": "kaggle.com",
  "TC": "topcoder.com",
  "FBHC": "facebook.com/hackercup"
}